apiVersion: v1
kind: Secret
metadata:
  name: cluster-autoscaler-cloud-config
  namespace: kube-system
type: Opaque
stringData:
  cloud-config: |-
    {
      "cluster_id": "00000000-0000-0000-0000-000000000000",
      "token": "replace-with-a-vultr-api-token"
    }
